/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_snso_helloworld_GetCinfo_CBackInterface */

#ifndef _Included_com_snso_helloworld_GetCinfo_CBackInterface
#define _Included_com_snso_helloworld_GetCinfo_CBackInterface
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
