/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_snso_helloworld_GetCinfo */

#ifndef _Included_com_snso_helloworld_GetCinfo
#define _Included_com_snso_helloworld_GetCinfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_snso_helloworld_GetCinfo
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_snso_helloworld_GetCinfo_getStr
  (JNIEnv *, jclass);

/*
 * Class:     com_snso_helloworld_GetCinfo
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_snso_helloworld_GetCinfo_getInt
  (JNIEnv *, jclass);

/*
 * Class:     com_snso_helloworld_GetCinfo
 * Method:    LedCtrl
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_snso_helloworld_GetCinfo_LedCtrl
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_snso_helloworld_GetCinfo
 * Method:    PwmCtrl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_snso_helloworld_GetCinfo_PwmCtrl
  (JNIEnv *, jclass);

/*
 * Class:     com_snso_helloworld_GetCinfo
 * Method:    callBack
 * Signature: (Lcom/snso/helloworld/GetCinfo/CBackInterface;)V
 */
JNIEXPORT void JNICALL Java_com_snso_helloworld_GetCinfo_callBack
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
